### ISSUE TITLE
Download the code

### ISSUE THREAD

**Issue by Ziemnono** [Ziemnono/LandmarkTracking_RGBD#1]
@jako2 when you have time can you try to:

1. Download the code using ```git clone git@github.com:Ziemnono/LandmarkTracking_RGBD.git```
2. Try to make a change in a file or add a file
3. Try to commit and push it in the main branch (it shouldn't work I just want to see if I successfully protected the main branch)

**Comment by jako2** [comment]
After installing all of the necessary packages to allow main.py to run error-free, I made a minor change to the program and attempted to commit and push it to the main branch. As expected, the push was rejected:

! [remote rejected] main -> main (protected branch hook declined)

**Comment by Ziemnono** [comment]
Perfect !
